#! /bin/bash

# tmclose
# Author: Austin Burt
# Email: austin@burt.us.com
# Date: 4/5/19
# github: github.com/arburty/tmsetup-commnand

declare -r PROGRAM=$(basename $0)


mySession() {
    name=$(tmux list-sessions | grep \(attached\)$ | cut -d ":" -f 1)
    echo $name
}

isValidSession() {
    # if it's not a session, its invalid.
    # let the tmux error print as a warning
    tmux has-session -t $1 || return 1
}

killSession() {
    isValidSession $1 && echo "Killing: $name" && tmux kill-session -t $1
}

kill_others() {
    otherSessions=$( tmux list-sessions -F '#S' | grep -v "$mine" )

    # kill all other sessions that are not mine
    while read currSession
    do
        name=$currSession
        sleep 0.5
        killSession $name
    done < <(echo "$otherSessions")
}

kill_mine() {
    # kill the session I am in last
    echo "Killing Session You Are In!"
    sleep 2
    killSession $mine

}

kill_all() {
    kill_others
    kill_mine
}

kill_list() {
    while [[ $# -gt 0 ]]; do
        killSession $1
        shift
    done
}

# Main {
mine=$(mySession)
[[ $# -eq 0 ]] && kill_mine
case $1 in
    -o ) kill_others    ;;
    -a ) kill_all       ;;
    *  ) kill_list "$@" ;;
esac # {

exit 0
