#! /bin/bash

# either give the session a name as the only argument or workspace is used
declare -r NAME=${1:-"workspace"}

tmux has-session -t $NAME 2>/dev/null
if [[ $? != 0 ]]; then
    tmux new -s ${NAME} -n workstation -d
    tmux split-window -v -t $NAME

    tmux new-window -n vim -t $NAME

    tmux new-window -n extra -t $NAME
    # cause why not?
    tmux send-keys -t $NAME 'clear' C-m 'figlet -f smslant.flf How u doin sweet cheeks?' C-m

    # 2 window switches so 'vim' is the last-window
    tmux select-window -t ${NAME}:2
    tmux select-window -t ${NAME}:1

    tmux send-keys -t $NAME 'clear' C-m 'git branch' C-m
    tmux send-keys -t $NAME 'git status' C-m
    tmux select-pane -U
fi

tmux attach -t $NAME
exit 0
